### ISSUE TITLE
Where's the README / project description / informative website ? 

### ISSUE THREAD

**Issue by edouard-sn** [Bedrock-im/bedrock#56]
🤨

**Comment by RezaRahemtola** [comment]
Hello @edouard-sn 👋 

This project is still very early stages, that's why it was previously lacking documentation.
You can now find a description, topics, the link to the production deployment (unstable, I don't recommend using it, we'll make an announcement in the releases when it will be stable), a README explaining the project origins and objectives and a basic documentation at https://docs.bedrock.im that will soon contain technical details about Bedrock.

**Comment by edouard-sn** [comment]
Nice, I hope to be cited in your next EIP meeting :)
